<a href="https://colab.research.google.com/github/HowardJoshua-crypto/DPR_Agriculture_Retrieval_Experiment/blob/main/DPR_Agriculture_Retrieval_Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install -q rank-bm25 sentence-transformers pandas

**rank-bm25**:implements keyword-based retrieval(baseline)

**sentence-transformers**: generates text embeddings for dense retrieval

**pandas**:organise passages, questions, and results in dataframes.

In [6]:
import pandas as pd
passages = [
    {
        "passage_id": "AGR001",
        "text": (
            "Maize requires nitrogen for healthy vegetative growth. "
            "Nitrogen deficiency can cause yellowing of older leaves "
            "and reduce crop productivity."
        )
    },
    {
        "passage_id": "AGR002",
        "text": (
            "Soil testing helps farmers determine soil pH and nutrient "
            "availability before selecting fertilizer applications."
        )
    },
    {
        "passage_id": "AGR003",
        "text": (
            "Crop rotation with legumes can contribute nitrogen to "
            "agricultural systems and help improve soil fertility."
        )
    },
    {
        "passage_id": "AGR004",
        "text": (
            "Drought stress occurs when water availability is "
            "insufficient for normal plant growth and development."
        )
    },
    {
        "passage_id": "AGR005",
        "text": (
            "Integrated pest management combines monitoring, "
            "preventive practices, and appropriate pest control "
            "methods to reduce crop damage."
        )
    },
    {
        "passage_id": "AGR006",
        "text": (
            "Organic matter can improve soil structure, water "
            "retention, and conditions for soil organisms."
        )
    },
    {
        "passage_id": "AGR007",
        "text": (
            "Excessive fertilizer application may cause nutrient "
            "losses through runoff or leaching into water systems."
        )
    },
    {
        "passage_id": "AGR008",
        "text": (
            "Early planting can help crops use available seasonal "
            "rainfall, although suitable planting dates depend on "
            "local climate and crop variety."
        )
    }
]
corpus_df =pd.DataFrame(passages)
print("Number of passages: ",len(corpus_df))
display( corpus_df)

Number of passages:  8

  passage_id                                               text
0     AGR001  Maize requires nitrogen for healthy vegetative...
1     AGR002  Soil testing helps farmers determine soil pH a...
2     AGR003  Crop rotation with legumes can contribute nitr...
3     AGR004  Drought stress occurs when water availability ...
4     AGR005  Integrated pest management combines monitoring...
5     AGR006  Organic matter can improve soil structure, wat...
6     AGR007  Excessive fertilizer application may cause nut...
7     AGR008  Early planting can help crops use available se...

A *dataframe* containing 8 rows of *passages* wach with a unique **ID** to help identify exactly which passage the retrieval system found.

In [13]:
import re
from rank_bm25 import BM25Okapi

def tokenize(text):
    return re.findall(r"\b\w+\b", text.lower())

passage_texts =corpus_df["text"].tolist()
tokenised_passages =[tokenize(text) for text in passage_texts]
bm25 = BM25Okapi(tokenised_passages)

question1="How can farmers improve nitrogen availability in soil?"
question2="What crop management practices help maintain fertile soil?"

#Test question1
scores=bm25.get_scores(tokenize(question1))

ranked_indices =sorted(
    range(len(scores)),
    key=lambda i: scores[i],
    reverse=True
)
for rank, i in enumerate(ranked_indices[:5],start=1):
  print(f"Rank {rank} |" f"{corpus_df.iloc[i]['passage_id']} | " f"Score: {scores[i]: 4f}")
  print(corpus_df.iloc[i]['text'])
  print()

Rank 1 |AGR002 | Score:  3.358907
Soil testing helps farmers determine soil pH and nutrient availability before selecting fertilizer applications.

Rank 2 |AGR003 | Score:  2.406322
Crop rotation with legumes can contribute nitrogen to agricultural systems and help improve soil fertility.

Rank 3 |AGR006 | Score:  1.716207
Organic matter can improve soil structure, water retention, and conditions for soil organisms.

Rank 4 |AGR001 | Score:  1.276398
Maize requires nitrogen for healthy vegetative growth. Nitrogen deficiency can cause yellowing of older leaves and reduce crop productivity.

Rank 5 |AGR004 | Score:  1.002425
Drought stress occurs when water availability is insufficient for normal plant growth and development.

A display of five **highest** ranked *passages* measured based on **lexical relevance** rather than probability that a passage contains the correct answer.

In [14]:
import re
from rank_bm25 import BM25Okapi

def tokenize(text):
    return re.findall(r"\b\w+\b", text.lower())

passage_texts =corpus_df["text"].tolist()
tokenised_passages =[tokenize(text) for text in passage_texts]
bm25 = BM25Okapi(tokenised_passages)

question1="How can farmers improve nitrogen availability in soil?"
question2="What crop management practices help maintain fertile soil?"

#Test question2
scores=bm25.get_scores(tokenize(question2))

ranked_indices =sorted(
    range(len(scores)),
    key=lambda i: scores[i],
    reverse=True
)
for rank, i in enumerate(ranked_indices[:5],start=1):
  print(f"Rank {rank} |" f"{corpus_df.iloc[i]['passage_id']} | " f"Score: {scores[i]: 4f}")
  print(corpus_df.iloc[i]['text'])
  print()

Rank 1 |AGR005 | Score:  3.184483
Integrated pest management combines monitoring, preventive practices, and appropriate pest control methods to reduce crop damage.

Rank 2 |AGR003 | Score:  1.433296
Crop rotation with legumes can contribute nitrogen to agricultural systems and help improve soil fertility.

Rank 3 |AGR008 | Score:  0.848589
Early planting can help crops use available seasonal rainfall, although suitable planting dates depend on local climate and crop variety.

Rank 4 |AGR006 | Score:  0.682551
Organic matter can improve soil structure, water retention, and conditions for soil organisms.

Rank 5 |AGR002 | Score:  0.668024
Soil testing helps farmers determine soil pH and nutrient availability before selecting fertilizer applications.

In [15]:
from sentence_transformers import SentenceTransformer
import numpy as np
import torch

MODEL_ID="sentence-transformers/all-MiniLM-L6-v2"
model= SentenceTransformer(MODEL_ID)
print("Model: ", MODEL_ID)
print("Device: ",model.device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model:  sentence-transformers/all-MiniLM-L6-v2
Device:  cpu

**Dense Retrieval** converts each passage into a numerical ventor

In [17]:
passage_texts=corpus_df["text"].tolist()

passage_embeddings=model.encode(
    passage_texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("Embedding shape: ",passage_embeddings.shape)
print("First passage vector:")
print(passage_embeddings[0][:10])

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding shape:  (8, 384)
First passage vector:
[-0.05481549  0.05253794  0.00608619  0.0119704   0.1385181   0.04906064
 -0.02099696 -0.04533541 -0.05859482  0.02476801]

In [18]:

def dense_search(question, top_k=5):
    query_embedding = model.encode(
        [question],
        convert_to_numpy=True,
        normalize_embeddings=True
    )[0]

    # Normalized vectors make dot product equivalent
    # to cosine similarity.
    scores = passage_embeddings @ query_embedding

    ranked_indices = np.argsort(scores)[::-1][:top_k]

    results = []

    for rank, i in enumerate(ranked_indices, start=1):
        results.append({
            "rank": rank,
            "passage_id": corpus_df.iloc[i]["passage_id"],
            "score": float(scores[i]),
            "text": corpus_df.iloc[i]["text"]
        })

    return pd.DataFrame(results)


question = "How can farmers improve nitrogen availability in soil?"

dense_results = dense_search(question)

display(dense_results)

,rank,passage_id,score,text
0,1,AGR003,0.643092,Crop rotation with legumes can contribute nitr...
1,2,AGR002,0.588523,Soil testing helps farmers determine soil pH a...
2,3,AGR001,0.581701,Maize requires nitrogen for healthy vegetative...
3,4,AGR006,0.500620,"Organic matter can improve soil structure, wat..."
4,5,AGR007,0.427201,Excessive fertilizer application may cause nut...

In [19]:

question = "How can farmers improve nitrogen availability in soil?"

# BM25 ranking
bm25_scores = bm25.get_scores(tokenize(question))
bm25_order = np.argsort(bm25_scores)[::-1][:5]

bm25_results = pd.DataFrame([
    {
        "rank": rank,
        "passage_id": corpus_df.iloc[i]["passage_id"],
        "score": float(bm25_scores[i])
    }
    for rank, i in enumerate(bm25_order, start=1)
])

# Dense ranking
dense_results = dense_search(question)[
    ["rank", "passage_id", "score"]
]

print("BM25 results")
display(bm25_results)

print("Dense retrieval results")
display(dense_results)

BM25 results

   rank passage_id     score
0     1     AGR002  3.358907
1     2     AGR003  2.406322
2     3     AGR006  1.716207
3     4     AGR001  1.276398
4     5     AGR004  1.002425

Dense retrieval results

   rank passage_id     score
0     1     AGR003  0.643092
1     2     AGR002  0.588523
2     3     AGR001  0.581701
3     4     AGR006  0.500620
4     5     AGR007  0.427201